#ifndef CMESH_NO_IGL_INTERFACE_1604911737496_H
#define CMESH_NO_IGL_INTERFACE_1604911737496_H
#include "ccglobal/export.h"

#ifdef USE_CMESH_NOIGL_DLL
	#define CMESH_NOIGL_API CC_DECLARE_IMPORT
#elif USE_CMESH_NOIGL_STATIC
	#define CMESH_NOIGL_API CC_DECLARE_STATIC
#else
	#ifdef CMESH_NOIGL_DLL
	#define CMESH_NOIGL_API CC_DECLARE_EXPORT
	#else
	#define CMESH_NOIGL_API CC_DECLARE_STATIC
	#endif
#endif

#define CMESH_API CMESH_NOIGL_API

#endif // CMESH_NO_IGL_INTERFACE_1604911737496_H